# --- 1. SUPABASE (OBRIGATÃ“RIO: NO TOPO DO ARQUIVO) ---
SUPABASE_URL = "https://eyyqaqtqylpmvhcfvtmn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5eXFhcXRxeWxwbXZoY2Z2dG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTE1ODQsImV4cCI6MjA4NTAyNzU4NH0.R7F1BYe4jTEt9OG6C_kAyESMG2jhOH2RWc90QtZTFcU"

# --- 2. PLUGGY (EMBAIXO) ---
PLUGGY_CLIENT_ID = "093721db-5e48-4df7-a14a-37d93533f003"
PLUGGY_CLIENT_SECRET = "68d306f7-56af-4184-8952-422b4bffe6ad"
